plugins:
  -
    - '@semantic-release/commit-analyzer'
    - preset: eslint
  -
    - '@semantic-release/release-notes-generator'
    - preset: eslint
  -
    - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
  -
    - '@semantic-release/exec'
    - prepareCmd: >
        make CLI_DIST_VERSION=${nextRelease.gitTag} dist
  -
    - '@semantic-release/git'
    - assets:
      - CHANGELOG.md
      message: >
        Chore: Release ${nextRelease.version}

        ${nextRelease.notes}
  -
    - '@semantic-release/github'
    - assets:
      - 'artifacts/*'
      successComment: false
      failComment: false
      releasedLabels: false
  -
    - '@semantic-release/exec'
    - publishCmd: >
        make CLI_DIST_VERSION=${nextRelease.gitTag} release
